### ISSUE TITLE
Improve hapi-sequelized SEO on npmjs.com

### ISSUE THREAD

**Issue by tribou** [danecando/hapi-sequelized#12]
When you search for "hapi sequelize" on npmjs.com, `hapi-sequelized` comes up on page 4.  Perhaps adding more keywords to the `package.json` will help.  Matching some of the ones used by Sequelize and others may help target the appropriate users:

```json
[
    "mysql",
    "sqlite",
    "postgresql",
    "postgres",
    "mssql",
    "orm",
    "plugin",
    "database"
]
```

However, it doesn't make sense that some modules with nothing to do with sequelize are ranking higher than this one.

**Comment by danecando** [comment]
Thanks @tribou. I'm going to get in touch with someone from npm and see what they recommend. And we'll take it from there!

**Comment by danecando** [comment]
I was told by their senior engineer that their search is pretty bad. She told me to open an issue about it so: https://github.com/npm/newww/issues/739

Doesn't seem like we're going to get much help but I guess we'll see...

**Comment by danecando** [comment]
Added some keywords. Looks like we will just have to wait for them to improve their search functionality though.
