### ISSUE TITLE
Expose Models on request

### ISSUE THREAD

**Issue by mikeburgh** [danecando/hapi-sequelized#24]
Any thoughts to exposing the models on the request object.. something like:

```javascript
server.ext('onPreHandler', function(modelCollections) {
	return function(request, reply) {
		request.models = modelCollections;
		reply.continue();
	}
}(server.plugins['hapi-sequelized'].db.sequelize.models));
```

Then in routes you can get a model:
request.models.modelname ?

**Comment by danecando** [comment]
Hey @mikeburgh 

Good thought and example. I'm curious if we should add this snippet in the README as an example for users that would like to do this instead of adding it to the plugin. This way they can have the choice of whether or not they want to duplicate the models object.

**Comment by mikeburgh** [comment]
That works!

I just created a PR, but failed to tag it to this issue! sorry about that.
