### ISSUE TITLE
Allow additional constructor options to be provided 

### ISSUE THREAD

**Issue by wallance** [danecando/hapi-sequelized#9]
Can the functionality of this plugin be extended to allow the additional documented options to be passed to the Sequelize constructor?

For example, it would be nice to set the ```timestamps``` option globally, instead of for each model, like the Sequelize documentation allows:

http://sequelize.readthedocs.org/en/latest/docs/getting-started/#application-wide-model-options

In addition to model settings, it would also be convenient to be allowed to pass all the other Sequelize constructor options such ```options.logging```, ```options.replication```, etc

**Comment by tribou** [comment]
Could we also get `host` added to the list of options?  Currently, (unless I'm missing it somewhere), hapi-sequelized only allows for the default `localhost` to be passed through the options.

**Comment by danecando** [comment]
@tribou @wallance thanks for the heads up guys. I'll have this added asap

**Comment by danecando** [comment]
haven't tested yet but that should do it ^. I will test it out and add new options to the readme later
